### PR TITLE
Only restartChecks if pod is master for configReloader

### LINKED ISSUE #925: Checks are getting scheduled at nearly the same time.
**Describe the bug**
A KHC will get scheduled twice -- one after the other within milliseconds:
image
image
image

This always forces the one that is scheduled first to fail / error due to an invalid check uuid resulting in a rejection from the Kuberhealthy master and a `400 Bad Request` from the checker pod.

**Steps To Reproduce**
- Run a deployment of kuberhealthy with `latest` tag
- That container's digest for reference: `sha256:e03e18490bd87e162d2c3a51a7f7f8c6bdd1a883af90b0a7e9a6ea4ef40d1c42` (Today is May 10, 2021)

**Expected behavior**
Normal Kuberhealthy check lifecycle (single checker pod -> check -> report) 

**Versions**
 - Kubernetes Version: 1.11.7

### PR DESCRIPTION
**Pull request by joshulyne**
Fixes #925

### CODE REVIEW

**Comment by integrii** [comment]
Great find!  I feel like this one should go into a different place, though.

Check out the `control` code [here](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/kuberhealthy/kuberhealthy.go#L218).  This control loop is responsible for doing various check starts and stops and reloads.  It feels like the `configReloader` func should be refactored to return a channel, then after reloading configuration, it should notify the channel that configuration has changed.  That signal would go into the switch in the `control` code loop and result in this reload (but only if master!).

This way we have a central place to manage all reloading and check start/stopping control flow...

**Comment by integrii** [comment]
You could probably move the config reloader goroutine to be just above the control flow... up where there call to `monitorKHJobs()` is...

**Comment by joshulyne** [comment]
> Great find! I feel like this one should go into a different place, though.
> 
> Check out the `control` code [here](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/kuberhealthy/kuberhealthy.go#L218). This control loop is responsible for doing various check starts and stops and reloads. It feels like the `configReloader` func should be refactored to return a channel, then after reloading configuration, it should notify the channel that configuration has changed. That signal would go into the switch in the `control` code loop and result in this reload (but only if master!).
> 
> This way we have a central place to manage all reloading and check start/stopping control flow...

makes sense! will refactor to do so!

File: cmd/kuberhealthy/kuberhealthy.go [hunk 1]
```diff
@@ -236,6 +243,14 @@ func (k *Kuberhealthy) Start(ctx context.Context) {
 				k.RestartChecks(ctx)
 				k.RestartReaper(ctx)
 			}
+		case <-configReloadChan:
+			log.Infoln("control: Witnessed a kuberhealthy configuration change...")
+
+			// if we are master, stop, reconfigure our khchecks, and start again with the new configuration
+			if isMaster {
+				log.Infoln("control: Reloading external check configurations due to kuberhealthy configuration update")
+				k.RestartChecks(ctx)
```
Comment (joshulyne) [inline cmd/kuberhealthy/kuberhealthy.go:252]: @integrii should we also be restarting the Reaper -- like in the case above? 
https://github.com/kuberhealthy/kuberhealthy/pull/942/files#diff-6fe2eb1bda3003e83c281ea43553e293915389e31314d523116afe24efe877e3R244

Comment (integrii) [reply cmd/kuberhealthy/kuberhealthy.go:252]: I would restart the reaper just in case.  This way we are more likely to make any new configuration options that have been set for it take effect.

File: cmd/kuberhealthy/config.go [hunk 2]
```diff
@@ -154,8 +154,8 @@ func startConfigReloadMonitoringWithSmoothing(filePath string, scrapeInterval ti
 	return outChan, cancelFunc, nil
 }
 
-// configReloader watchers for events in file and restarts kuberhealhty checks
-func configReloader(ctx context.Context, kh *Kuberhealthy) {
+// configReloadNotifier watchers for events in file, reloads the configuration, and notifies upstream to restart checks
```
Comment (integrii) [inline cmd/kuberhealthy/config.go:157]: This is really good, but it looks like `configReloadNotifier` will run forever.  This means that every time `kuberhealthy.Start()` is called, a new go routine will be spawned that never shuts down.  That is a very uncommon thing, but not impossible.

can you add a context here, then pass in the context when this routine is spawned?  Then, check if the context has expired and `return` if it has.

**Review by integrii — CHANGES_REQUESTED** [review]

**Review by jonnydawg — APPROVED** [review]
thanks!
